donghunseol/yeogi_copy

- src/main/java/com/example/final_project/room_information/RoomInformation.java
> room_information entity 완료

- src/main/java/com/example/final_project/review_comment/ReviewComment.java
> review_comment entity 완료

- src/main/java/com/example/final_project/_core/enums/RoomEnum.java
- src/main/java/com/example/final_project/company/Company.java
- src/main/java/com/example/final_project/room/Room.java
- src/main/java/com/example/final_project/room_information/RoomInformation.java
- src/main/java/com/example/final_project/user/User.java
- src/main/resources/db/data.sql
> 더미 생성 및 엔티티 수정(temp)

- src/main/java/com/example/final_project/_core/enums/PayEnum.java
- src/main/java/com/example/final_project/pay/Pay.java
> pay entity 완료

- src/main/java/com/example/final_project/_core/utils/DateUtil.java
- src/main/java/com/example/final_project/reservation/Reservation.java
- src/test/java/com/example/final_project/_core/utils/DateUtilTest.java
reservation entity 수정 + 관련 파일 수정
> reservation entity 수정 + 관련 파일 수정

- src/main/java/com/example/final_project/reservation/Reservation.java
- src/main/java/com/example/final_project/reservation/ReservationController.java
- src/main/java/com/example/final_project/reservation/ReservationRepository.java
> rereservation entity 수정 완료

- src/main/java/com/example/final_project/reservation/ReservationController.java
- src/test/java/com/example/final_project/reservation/ReservationRepositoryTest.java
findByUserIdWithRoomAndStay test 완료
> findByUserIdWithRoomAndStay test 완료

- src/main/java/com/example/final_project/company/CompanyController.java
- src/main/java/com/example/final_project/reservation/ReservationRepository.java
- src/main/java/com/example/final_project/reservation/ReservationService.java
- src/main/java/com/example/final_project/user/UserController.java
- src/test/java/com/example/final_project/reservation/ReservationRepositoryTest.java
- src/test/java/com/example/final_project/reservation/ReservationServiceTest.java
> 기업의 예약 현황 확인 구현 환료

- src/main/java/com/example/final_project/admin/AdminResponse.java
- src/main/java/com/example/final_project/admin/AdminService.java
- src/test/java/com/example/final_project/admin/AdminServiceTest.java
> 모든 개인 유저의 정보 리스트 출력 구현

- src/main/java/com/example/final_project/admin/AdminService.java
- src/test/java/com/example/final_project/admin/AdminServiceTest.java
> 특정 개인 회원의 예약 정보 리스트 출력 구현

- src/main/java/com/example/final_project/admin/AdminResponse.java
- src/main/java/com/example/final_project/admin/AdminService.java
- src/test/java/com/example/final_project/admin/AdminServiceTest.java
> 모든 기업 리스트 출력 구현

- src/main/java/com/example/final_project/admin/AdminService.java
- src/test/java/com/example/final_project/admin/AdminServiceTest.java
> 개인 회원을 블랙 리스트에 추가하는 기능 구현

- src/main/java/com/example/final_project/admin/AdminService.java
- src/test/java/com/example/final_project/admin/AdminServiceTest.java
> 기업 회원을 블랙 리스트에 추가하는 기능 구현

- src/main/java/com/example/final_project/admin/AdminService.java
- src/main/java/com/example/final_project/review/ReviewRepository.java
- src/test/java/com/example/final_project/admin/AdminServiceTest.java
- src/test/java/com/example/final_project/review/ReviewRepositoryTest.java
> Admin/list review/sjm

- src/main/java/com/example/final_project/admin/AdminResponse.java
- src/main/java/com/example/final_project/admin/AdminService.java
- src/main/java/com/example/final_project/room/RoomRepository.java
- src/main/java/com/example/final_project/stay/Stay.java
- src/main/java/com/example/final_project/stay/StayRepository.java
- src/test/java/com/example/final_project/admin/AdminServiceTest.java
- src/test/java/com/example/final_project/room/RoomRepositoryTest.java
- src/test/java/com/example/final_project/stay/StayRepositoryTest.java
> Admin/list stay/sjm

- src/main/java/com/example/final_project/_core/enums/CompanyEnum.java
- src/main/java/com/example/final_project/admin/AdminService.java
- src/test/java/com/example/final_project/admin/AdminServiceTest.java
> 기업 심사 거절 구현

- src/main/java/com/example/final_project/_core/enums/CompanyEnum.java
- src/main/java/com/example/final_project/reservation/ReservationService.java
- src/test/java/com/example/final_project/admin/AdminServiceTest.java
> 기업 심사 거절 구현(pull했음)

- src/main/java/com/example/final_project/admin/AdminService.java
- src/test/java/com/example/final_project/admin/AdminServiceTest.java
> 기업 심사 승인 구현(+거절 테스트 수정)

- src/main/java/com/example/final_project/reservation/ReservationResponse.java
- src/main/java/com/example/final_project/user/UserController.java
- src/test/java/com/example/final_project/reservation/ReservationServiceTest.java
> 개인 - 예약 내역 조회(목록) 코드 수정

- src/main/java/com/example/final_project/reservation/ReservationController.java
- src/main/java/com/example/final_project/reservation/ReservationResponse.java
- src/main/java/com/example/final_project/user/UserController.java
> 개인 - 예약 내역 조회(상세보기) 코드 수정

- src/main/java/com/example/final_project/company/CompanyController.java
- src/main/java/com/example/final_project/company/CompanyRepository.java
- src/main/java/com/example/final_project/company/CompanyResponse.java
- src/main/java/com/example/final_project/company/CompanyService.java
- src/main/resources/templates/company/stay/detail.mustache
- src/main/resources/templates/company/stay/main.mustache
> Company/list stay/sjm

- src/main/java/com/example/final_project/company/CompanyController.java
- src/main/java/com/example/final_project/company/CompanyResponse.java
- src/main/java/com/example/final_project/company/CompanyService.java
- src/main/java/com/example/final_project/pay/PayRepository.java
- src/main/resources/static/css/style.css
- src/main/resources/templates/company/room/detail.mustache
> Company/list room/sjm

- src/main/java/com/example/final_project/company/CompanyController.java
- src/main/java/com/example/final_project/company/CompanyResponse.java
- src/main/java/com/example/final_project/company/CompanyService.java
- src/main/java/com/example/final_project/reservation/ReservationRepository.java
- src/main/resources/templates/company/reservation/detail.mustache
- src/main/resources/templates/company/room/detail.mustache
- src/test/java/com/example/final_project/company/CompanyServiceTest.java
- src/test/java/com/example/final_project/reservation/ReservationRepositoryTest.java
Company/detail reservation/sjm
> Company/detail reservation/sjm

- src/main/java/com/example/final_project/admin/AdminController.java
> merge conflict 해결

- src/main/java/com/example/final_project/admin/AdminController.java
- src/main/java/com/example/final_project/admin/AdminResponse.java
- src/main/resources/templates/admin/customer-u/join.mustache
- src/test/java/com/example/final_project/admin/AdminServiceTest.java
> Admin/list user/sjm

- src/main/resources/templates/company/stay/detail.mustache
> company 뷰 오류 해결

- src/main/java/com/example/final_project/admin/AdminController.java
- src/main/java/com/example/final_project/admin/AdminService.java
- src/main/java/com/example/final_project/review/ReviewController.java
- src/main/java/com/example/final_project/review/ReviewService.java
- src/main/resources/templates/company/review/main.mustache
- src/main/resources/templates/company/stay/main.mustache
> Company/list review/sjm

- src/main/resources/templates/company/reservation/main.mustache
> 예약 현황 뷰 수정

- src/main/java/com/example/final_project/admin/AdminController.java
- src/main/java/com/example/final_project/company/CompanyResponse.java
- src/main/resources/templates/admin/layout/side.mustache
- src/main/resources/templates/admin/login.mustache
> 뷰 파일의 링크 수정 및 코드 순서 정리

- src/main/java/com/example/final_project/admin/AdminController.java
- src/main/java/com/example/final_project/admin/AdminResponse.java
- src/main/java/com/example/final_project/admin/AdminService.java
- src/main/java/com/example/final_project/company/CompanyController.java
- src/main/java/com/example/final_project/user/UserController.java
- src/main/resources/templates/admin/customer-c/stay-list.mustache
- src/test/java/com/example/final_project/admin/AdminServiceTest.java
> Admin/company stay list/sjm

- src/main/java/com/example/final_project/admin/AdminController.java
- src/main/java/com/example/final_project/admin/AdminResponse.java
- src/main/java/com/example/final_project/admin/AdminService.java
- src/main/resources/templates/admin/customer-c/join-detail.mustache
- src/main/resources/templates/admin/customer-c/join.mustache
- src/main/resources/templates/admin/login.mustache
- src/test/java/com/example/final_project/admin/AdminServiceTest.java
> admin/list company/sjm

- src/main/java/com/example/final_project/_core/utils/ImageUtil.java
> ImageUtil 주석 달기

- src/main/java/com/example/final_project/review/Review.java
- src/main/java/com/example/final_project/review/ReviewRepository.java
- src/main/java/com/example/final_project/stay/StayResponse.java
- src/main/java/com/example/final_project/stay/StayRestController.java
- src/main/java/com/example/final_project/stay/StayService.java
- src/test/java/com/example/final_project/stay/StayServiceTest.java
> User/stay detail/sjm

- src/main/java/com/example/final_project/stay/StayService.java
유저가 숙소를 클릭 했을 때 보여지는 숙소 상세보기 구현 코드 수정 완료
> 유저가 숙소를 클릭 했을 때 보여지는 숙소 상세보기 구현 코드 수정 완료

- src/main/java/com/example/final_project/reservation/ReservationResponse.java
> 예약 목록에서 숙박 날짜 수 제거

- src/main/resources/static/css/style.css
- src/main/resources/templates/company/room/detail.mustache
- src/test/java/com/example/final_project/stay/StayRepositoryTest.java
> All/update code/sjm

- src/main/java/com/example/final_project/company/CompanyResponse.java
- src/main/resources/templates/company/reservation/main.mustache
> reservation 리스트에 예약현황 추가

- src/main/java/com/example/final_project/admin/AdminController.java
- src/main/java/com/example/final_project/admin/AdminResponse.java
- src/main/java/com/example/final_project/admin/AdminService.java
- src/main/resources/templates/admin/customer-c/join-detail.mustache
- src/test/java/com/example/final_project/admin/AdminServiceTest.java
> [관리자] - [기업] 가입 승인거절 구현

- src/main/resources/static/css/style.css
- src/main/resources/templates/admin/customer-c/join-detail.mustache
Admin/company active reject/sjm
> Admin/company active reject/sjm

- src/main/java/com/example/final_project/reservation/ReservationResponse.java
- src/main/java/com/example/final_project/reservation/ReservationService.java
- src/main/java/com/example/final_project/user/UserController.java
- src/test/java/com/example/final_project/reservation/ReservationServiceTest.java
> 로그인 한 회원의 예약 내역 코드 수정

- src/main/java/com/example/final_project/pay/Pay.java
- src/main/java/com/example/final_project/reservation/ReservationResponse.java
> reservation response 수정

- src/main/java/com/example/final_project/scrap/ScrapRepository.java
- src/main/java/com/example/final_project/scrap/ScrapResponse.java
- src/main/java/com/example/final_project/scrap/ScrapRestController.java
- src/main/java/com/example/final_project/scrap/ScrapService.java
- src/test/java/com/example/final_project/scrap/ScrapRepositoryTest.java
> User/my scraps/sjm

- src/main/resources/templates/admin/customer-c/join-detail.mustache
- src/main/resources/templates/admin/customer-u/join-detail.mustache
- src/main/resources/templates/admin/customer-u/review/detail.mustache
- src/main/resources/templates/admin/customer-u/review/main.mustache
- src/main/resources/templates/admin/customer-u/review/report.mustache
> 관리자의 회원 상세보기 기능 오류 해결

- src/main/java/com/example/final_project/reservation/ReservationResponse.java
로그인한 회원의 예약 내역 페이지에 이미지 데이터 추가
> 로그인한 회원의 예약 내역 페이지에 이미지 데이터 추가

- src/main/java/com/example/final_project/admin/AdminResponse.java
- src/main/resources/templates/admin/review/report.mustache
> 신고 목록에 신고 현황 추가

- src/main/java/com/example/final_project/stay/StayResponse.java
StayDetail Response 수정 완료(주소, 위도, 경도 추가)
> StayDetail Response 수정 완료(주소, 위도, 경도 추가)
